name:  Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main

env:
  EC2_PUBLIC_IP0: 3.249.126.140
  EC2_PUBLIC_IP2: 3.252.200.173

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd polybot
          docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }}
          POLY_BOT_IMAGE_NAME=image_polybot_am_project:${{ github.run_number }}
          docker build -t $POLY_BOT_IMAGE_NAME .
          docker tag $POLY_BOT_IMAGE_NAME ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
          docker push ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME

  Deploy:
    name: Enhanced Deployment
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Deploy new version to EC2_0
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: ${{ env.EC2_PUBLIC_IP0 }}
          username: ubuntu
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
          scripts: |
            CONTAINER_NAME="my_polybot"
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
            docker run -d --name $CONTAINER_NAME -p 8443:8443 --restart always ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME

      - name: Deploy new version to EC2_2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: ${{ env.EC2_PUBLIC_IP2 }}
          username: ubuntu
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
          scripts: |
            CONTAINER_NAME="my_polybot"
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
            docker run -d --name $CONTAINER_NAME -p 8443:8443 --restart always ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
