name:  Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main

#env:
#  EC2_PUBLIC_IP0: 2.34.245.15.19
#  EC2_PUBLIC_IP2: 2.54.75.180.157

jobs:


  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          cd polybot
          docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }}
          POLY_BOT_IMAGE_NAME=image_polybot_am_project:${{ github.run_number }}
          docker build -t $POLY_BOT_IMAGE_NAME .
          docker tag $POLY_BOT_IMAGE_NAME ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
          docker push ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME

  Deploy:
    name: Enhanced Deployment
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Deploy new version to EC2_0

        run : |
          CONTAINER_NAME="my_polybot"
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@ec2-34-245-15-19.eu-west-1.compute.amazonaws.com "sudo docker stop my_polybot || true"
#        docker rm $CONTAINER_NAME || true
#          docker pull ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
#          docker run -d --name $CONTAINER_NAME -p 8443:8443 --restart always ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
#
#      - name: Deploy new version to EC2_2
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          host: ${{ env.EC2_PUBLIC_IP2 }}
#          username: ubuntu
#          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
#          run : |
#            CONTAINER_NAME="my_polybot"
#            docker stop $CONTAINER_NAME || true
#            docker rm $CONTAINER_NAME || true
#            docker pull ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
#            docker run -d --name $CONTAINER_NAME -p 8443:8443 --restart always ${{ secrets.DOCKER_REPO_USERNAME }}/$POLY_BOT_IMAGE_NAME
